services:
  nginx:
    container_name: web-nginx-app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8181:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80