name: CI-CD

on:
  push: 
    branches: ['main']
  workflow_dispatch: 
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Obtem codigo do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construcao e Envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: | 
            tavarescruz/nginx:latest
            tavarescruz/nginx:v${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Obtem codigo do projeto
        uses: actions/checkout@v4

      - name: configura Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          working-directory: terraform
          terraform_wrapper: false

      - name: Executa Arquivos Terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

